# Generated by Django 5.2.7 on 2025-11-20 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_options_alter_userfollows_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userfollows',
            name='followed_user',
        ),
        migrations.RemoveField(
            model_name='userfollows',
            name='user',
        ),
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.ticket'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('ticket',), name='unique_review_per_ticket'),
        ),
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
