# Generated by Django 4.2.16 on 2025-11-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_userfollows_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='author',
            field=models.CharField(blank=True, help_text="Nom de l'auteur du livre ou de l'article (facultatif).", max_length=128, verbose_name='Auteur'),
        ),
    ]
