# Generated by Django 4.2.16 on 2025-11-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_ticket_author'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_per_ticket',
        ),
    ]
