# Generated by Django 4.2.16 on 2025-12-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_review_unique_review_per_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-time_created'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
